services:
  dev:
    build:
      context: .
      args:
        GIT_USER_NAME: ${GIT_USER_NAME:-peter}
        GIT_USER_EMAIL: ${GIT_USER_EMAIL:-peter@peter.com}
    environment:
      OPENAI_API_KEY: "123" 
    container_name: dev
    userns_mode: keep-id
    devices:
      - nvidia.com/gpu=all
    group_add:
      - keep-groups
    ports:
      - "5000:5000"
      - "1455:1455"
      - "4096:4096"
    volumes:
      - ${HOME}/Projects:/home/ubuntu/Projects
      - dev-data:/data
    stdin_open: true
    tty: true

volumes:
  dev-data:
